export const colors = {
  COLOR_PRIMARY: "#f96163",
  COLOR_LIGHT: "#fff",
  COLOR_DARK: "#000",
  COLOR_DARK_ALT: "#262626",
};

export const categories = [
  {
    id: "01",
    category: "Desayunos",
    type: "breakfast",
  },
  {
    id: "02",
    category: "Almuerzos",
    type: "launch",
  },
  {
    id: "03",
    category: "Cenas",
    type: "dinner",
  },
  {
    id: "04",
    category: "Asiatico",
    type: "asian",
  },
  {
    id: "05",
    category: "Italiano",
    type: "italian",
  },
  {
    id: "06",
    category: "Postres",
    type: "desserts",
  },
  {
    id: "07",
    category: "Vegetariano",
    type: "vegetarian",
  },
  {
    id: "08",
    category: "Mariscos",
    type: "seafood",
  },
];

export const recipeList = [
  {
    id: "01",
    name: "Ensalada Rusa",
    image: require("../assets/images/ensalada_rusa.jpg"),
    rating: "4.2",
    type: "launch",
    ingredients: ["Atún fresco", "Jugo de lima", "Cebolla morada", "Aguacate"],
    time: "40 mins",
    difficulty: "Intermedio",
    calories: "420 cal",
    color: "#006A4E",
    description:
      "Un plato delicioso y refrescante que presenta atún fresco mezclado con el sabor del jugo de lima y la textura crujiente de la cebolla morada y el aguacate.",
    steps: [
      "Corte el atún fresco en pequeños cubos.",
      "Pique finamente la cebolla morada y el aguacate.",
      "Mezcle el atún, la cebolla morada y el aguacate en un tazón.",
      "Rocíe el jugo de lima sobre la mezcla y revuelva suavemente.",
      "Sirva frío y ¡disfrute!",
    ],
  },
  {
    id: "02",
    name: "Pan con Chicharrón",
    image: require("../assets/images/pan_chicharron.jpg"),
    rating: "4.2",
    type: "breakfast",
    ingredients: [
      "Pan francés",
      "Chicharrón de cerdo",
      "Camote",
      "Salsa criolla",
      "Mayonesa",
      "Lechuga",
    ],
    time: "40 mins",
    difficulty: "Intermedio",
    calories: "420 cal",
    color: "#3498db", // Color azul
    description:
      "Un clásico peruano que combina crujientes trozos de chicharrón de cerdo con camote, salsa criolla y mayonesa, todo servido en un pan francés fresco.",
    steps: [
      "Corte el pan francés por la mitad y retire parte del interior para hacer espacio para el relleno.",
      "Rellene el pan con trozos de chicharrón de cerdo y camote previamente cocido y cortado en rodajas.",
      "Añada una generosa porción de salsa criolla encima del chicharrón y el camote.",
      "Agregue una capa de lechuga fresca y luego una capa de mayonesa al gusto.",
      "Cierre el pan y presione suavemente para compactar los ingredientes.",
      "¡Sirva su Pan con Chicharrón peruano y disfrute de esta deliciosa combinación de sabores y texturas!",
    ],
  },
  {
    id: "03",
    name: "Panqueques",
    image: require("../assets/images/panqueques.png"),
    rating: "4.2",
    type: "breakfast",
    ingredients: [
      "Harina de trigo",
      "Leche",
      "Huevos",
      "Azúcar",
      "Polvo de hornear",
      "Sal",
      "Mantequilla",
    ],
    time: "40 mins",
    difficulty: "Intermedio",
    calories: "420 cal",
    color: "#DAA520",
    description:
      "Un desayuno delicioso y clásico que consiste en panqueques esponjosos, perfectos para acompañar con sirope de arce o tus ingredientes favoritos.",
    steps: [
      "En un tazón grande, mezcle la harina de trigo, el azúcar, el polvo de hornear y la sal.",
      "En otro tazón, bata los huevos y luego agregue la leche y la mantequilla derretida. Mezcle bien.",
      "Vierta la mezcla líquida en la mezcla de ingredientes secos y revuelva hasta que estén combinados. No mezcle demasiado; es normal que queden algunos grumos.",
      "Caliente una sartén antiadherente y unte un poco de mantequilla para evitar que los panqueques se peguen.",
      "Vierta un poco de masa en la sartén caliente para formar un panqueque. Cocine hasta que aparezcan burbujas en la superficie, luego voltee y cocine hasta que estén dorados en ambos lados.",
      "Repita el proceso con el resto de la masa hasta que haya hecho todos los panqueques deseados.",
      "Sirva los panqueques calientes con sirope de arce, frutas frescas, crema batida o sus ingredientes favoritos. ¡Disfrute de sus deliciosos panqueques caseros!",
    ],
  },
  {
    id: "02",
    name: "Tallarín Verde",
    image: require("../assets/images/tallarin_verde.png"),
    rating: "3.6",
    type: "launch",
    ingredients: [
      "Fideos de tallarín",
      "Albahaca fresca",
      "Espinacas",
      "Queso fresco",
      "Leche evaporada",
      "Ajo",
      "Aceite vegetal",
      "Sal y pimienta al gusto",
    ],
    time: "40 mins",
    difficulty: "Intermedio",
    calories: "420 cal",
    color: "#f39c12",
    description:
      "Un plato peruano clásico que combina fideos de tallarín en una cremosa salsa de albahaca y espinacas, servidos con queso fresco. ¡Una delicia!",
    steps: [
      "Cocine los fideos de tallarín según las instrucciones del paquete hasta que estén al dente. Luego, escúrralos y reserve.",
      "En una licuadora, combine albahaca fresca, espinacas, queso fresco, leche evaporada y ajo. Mezcle hasta obtener una salsa verde suave.",
      "En una sartén grande, caliente el aceite vegetal y agregue la salsa verde. Cocine a fuego medio hasta que la salsa espese y adquiera un color vibrante.",
      "Añada los fideos cocidos a la salsa y mezcle bien para que estén completamente cubiertos.",
      "Sazone con sal y pimienta al gusto y cocine por unos minutos más hasta que los fideos estén bien calientes.",
      "Sirva el Tallarín Verde caliente y disfrute de esta deliciosa especialidad peruana.",
    ],
  },
  {
    id: "04",
    name: "Manchurian",
    image: require("../assets/images/manchurian.png"),
    rating: "3.6",
    type: "asian",
    ingredients: ["Cauliflower", "Soy Sauce", "Ginger", "Garlic"],
    time: "30 mins",
    difficulty: "Easy",
    calories: "350 cal",
    color: "#d35400",
    description:
      "A popular Indo-Chinese dish featuring crispy cauliflower bites tossed in a flavorful sauce made with soy sauce, ginger, and garlic.",
    steps: [
      "Cut the cauliflower into florets and blanch them.",
      "Prepare a sauce by mixing soy sauce, ginger, and garlic.",
      "Deep-fry or shallow-fry the cauliflower until crispy.",
      "Toss the fried cauliflower in the sauce until well coated.",
      "Garnish with chopped green onions and serve hot.",
    ],
  },
  {
    id: "05",
    name: "Chicken",
    image: require("../assets/images/chicken.png"),
    rating: "2.2",
    type: "italian",
    ingredients: ["Chicken Breasts", "Salt", "Black Pepper", "Olive Oil"],
    time: "45 mins",
    difficulty: "Medium",
    calories: "450 cal",
    color: "#8d4004",
    description:
      "A succulent chicken dish seasoned with a blend of salt and black pepper, then cooked to perfection with a drizzle of olive oil.",
    steps: [
      "Preheat the oven to the specified temperature.",
      "Season the chicken breasts with salt and black pepper.",
      "Heat olive oil in a skillet over medium-high heat.",
      "Sear the chicken breasts on both sides until golden brown.",
      "Transfer the chicken to the oven and bake until cooked through.",
      "Serve hot and enjoy your flavorful chicken!",
    ],
  },
  {
    id: "06",
    name: "Cupcakes",
    image: require("../assets/images/cupcakes.png"),
    rating: "5.0",
    type: "desserts",
    ingredients: ["Flour", "Sugar", "Eggs", "Butter"],
    time: "60 mins",
    difficulty: "Medium",
    calories: "200 cal",
    description:
      "Delightful cupcakes made with a perfect blend of flour, sugar, eggs, and butter, perfect for any occasion.",
    steps: [
      "Preheat the oven to the specified temperature.",
      "Prepare the cupcake batter by mixing the ingredients together.",
      "Line a muffin tin with cupcake liners.",
      "Fill each liner with batter and bake in the oven.",
      "Let the cupcakes cool, then frost and decorate as desired.",
      "Indulge in these sweet treats and savor the flavor!",
    ],
  },
  {
    id: "07",
    name: "Curry",
    image: require("../assets/images/curry.png"),
    rating: "4.8",
    type: "vegetarian",
    ingredients: ["Meat", "Curry Powder", "Coconut Milk", "Spices"],
    time: "55 mins",
    difficulty: "Hard",
    calories: "550 cal",
    color: "#d35400",

    description:
      "A rich and aromatic curry dish featuring tender pieces of meat cooked in a flavorful blend of curry powder, coconut milk, and spices.",
    steps: [
      "Marinate the meat with spices and let it sit for a while.",
      "Heat oil in a large pot and sauté the marinated meat until browned.",
      "Add curry powder and stir to coat the meat.",
      "Pour in coconut milk and bring to a simmer.",
      "Cover and let the curry simmer until the meat is tender and the flavors meld.",
      "Serve the curry with rice or bread and enjoy the deliciousness!",
    ],
  },
  {
    id: "08",
    name: "Ramen",
    image: require("../assets/images/ramen-org.png"),
    rating: "4.2",
    type: "seafood",
    ingredients: ["Ramen Noodles", "Soy Sauce", "Eggs", "Vegetables"],
    time: "35 mins",
    difficulty: "Easy",
    calories: "400 cal",
    color: "#f96163",
    description:
      "A comforting bowl of ramen featuring slurp-worthy noodles, a savory soy sauce-based broth, tender vegetables, and perfectly boiled eggs.",
    steps: [
      "Boil the ramen noodles according to package instructions.",
      "In a pot, bring water to a simmer and add soy sauce for the broth.",
      "Add chopped vegetables and let them cook until tender.",
      "Boil eggs to your desired doneness, then peel and slice them.",
      "Assemble the ramen bowls by placing cooked noodles, vegetables, and egg slices.",
      "Ladle the hot broth over the ingredients and get ready to enjoy your homemade ramen!",
    ],
  },
  {
    id: "09",
    name: "Lomo Saltado",
    image: require("../assets/images/lomo_saltado.png"),
    rating: "4.7",
    type: "launch",
    ingredients: [
      "Filete de res",
      "Papas amarillas",
      "Cebolla roja",
      "Tomate",
      "Aji amarillo",
      "Salsa de soja",
      "Vinagre",
      "Ajo",
      "Comino",
      "Pimienta",
      "Cilantro fresco",
      "Arroz blanco",
    ],
    time: "25 mins",
    difficulty: "Fácil",
    calories: "450 cal",
    color: "#f96163",
    description:
      "Un reconfortante plato de Lomo Saltado con filete de res, papas amarillas, cebolla roja y tomate, todo salteado en una sabrosa mezcla de salsa de soja, vinagre y especias. Se sirve con arroz blanco y se decora con cilantro fresco.",
    steps: [
      "Corte el filete de res en tiras delgadas y sazónelo con ajo, comino y pimienta al gusto.",
      "En una sartén grande, caliente un poco de aceite y saltee el filete de res hasta que esté dorado. Retire de la sartén y reserve.",
      "En la misma sartén, agregue un poco más de aceite y saltee las papas amarillas cortadas en tiras hasta que estén doradas y crujientes. Luego, retire y reserve.",
      "Añada un poco de aceite más a la sartén y saltee la cebolla roja, el tomate y el aji amarillo hasta que estén tiernos.",
      "Regrese el filete de res y las papas amarillas a la sartén con las verduras. Añada salsa de soja y vinagre. Cocine por unos minutos para que todo se mezcle bien.",
      "Sirva el Lomo Saltado caliente sobre arroz blanco y decore con cilantro fresco. ¡Disfrute de su Lomo Saltado casero!",
    ],
  },
  {
    id: "10",
    name: "Aji de gallina",
    image: require("../assets/images/aji_gallina.jpeg"),
    rating: "4.5",
    type: "launch",
    ingredients: [
      "Pollo desmenuzado",
      "Ají amarillo",
      "Pan remojado en leche",
      "Nueces",
      "Queso fresco",
      "Papas cocidas",
      "Huevos duros",
      "Aceitunas negras",
      "Arroz blanco",
    ],
    time: "45 mins",
    difficulty: "Fácil",
    calories: "450 cal",
    color: "#006A4E",
    description:
      "Un reconfortante plato de ají de gallina, con pollo desmenuzado en una deliciosa salsa de ají amarillo, servido con papas cocidas, arroz blanco y decorado con huevos duros y aceitunas negras.",
    steps: [
      "En una cacerola grande, cocine el pollo desmenuzado en una mezcla de aceite y ají amarillo hasta que esté bien cocido.",
      "En una licuadora, mezcle el pan remojado en leche y las nueces hasta obtener una pasta suave.",
      "Agregue la mezcla de pan y nueces a la cacerola con el pollo y cocine a fuego lento, revolviendo constantemente, hasta que la mezcla se espese y obtenga una consistencia cremosa.",
      "Añada el queso fresco desmenuzado a la mezcla y cocine hasta que se derrita completamente.",
      "Sirva el ají de gallina caliente sobre papas cocidas y arroz blanco.",
      "Decore con huevos duros en rodajas y aceitunas negras antes de servir. ¡Disfrute de su ají de gallina casero!",
    ],
  },
  {
    id: "11",
    name: "Hot Dog",
    image: require("../assets/images/lasgana.png"),
    rating: "4.6",
    type: "dinner",
    ingredients: ["Hot Dog Buns", "Frankfurters", "Ketchup", "Mustard"],
    time: "40 mins",
    difficulty: "Medium",
    calories: "420 cal",
    color: "#FF0000",
    description:
      "A classic American favorite, hot dog buns stuffed with juicy frankfurters, drizzled with ketchup and mustard for that perfect balance of flavors.",
    steps: [
      "Grill or heat the frankfurters until they're cooked through.",
      "Place the frankfurters in hot dog buns.",
      "Squeeze ketchup and mustard over the frankfurters.",
      "Serve with your favorite sides and enjoy!",
    ],
  },
];
